/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.TreeSet;

/**
 *
 * @author Nuri
 */
public class VistaPrincipal extends javax.swing.JFrame {
    public static Directorio directorioGlobal = new Directorio();
    public static TreeSet<String> listaCiudades = new TreeSet<>();
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        listaCiudades.add("San Luis");
        listaCiudades.add("Villa Mercedes");
        listaCiudades.add("Merlo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mClientes = new javax.swing.JMenu();
        miAgregarcliente = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        miBuscarCliente = new javax.swing.JMenuItem();
        mDirectorio = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mCiudades = new javax.swing.JMenu();
        miAgregarCiudad = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        mClientes.setText("Clientes");

        miAgregarcliente.setText("Agregar Cliente");
        mClientes.add(miAgregarcliente);

        jMenuItem1.setText("Borrar Cliente");
        mClientes.add(jMenuItem1);

        miBuscarCliente.setText("Buscar Cliente");
        mClientes.add(miBuscarCliente);

        jMenuBar1.add(mClientes);

        mDirectorio.setText("Directorio");

        jMenuItem2.setText("Buscar Cliente por Ciudad");
        mDirectorio.add(jMenuItem2);

        jMenuItem3.setText("Buscar Telefono por Apellido");
        mDirectorio.add(jMenuItem3);

        jMenuBar1.add(mDirectorio);

        mCiudades.setText("Ciudades");
        mCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCiudadesActionPerformed(evt);
            }
        });

        miAgregarCiudad.setText("Agregar Ciudad");
        miAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgregarCiudadActionPerformed(evt);
            }
        });
        mCiudades.add(miAgregarCiudad);

        jMenuBar1.add(mCiudades);

        mSalir.setText("Salir");
        mSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSalirMouseClicked(evt);
            }
        });
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCiudadesActionPerformed

    }//GEN-LAST:event_mCiudadesActionPerformed

    private void miAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgregarCiudadActionPerformed
        jDesktopPane1.removeAll(); //aca al escritorio lo limpio por si hay una ventana abierta
        jDesktopPane1.repaint();
        AgregarCiudad vistaCiudad = new AgregarCiudad();//instancio la internalform
        vistaCiudad.setVisible(true); 
        jDesktopPane1.add(vistaCiudad);
       
    }//GEN-LAST:event_miAgregarCiudadActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
    System.exit(0); //cierra todo
    }//GEN-LAST:event_mSalirActionPerformed

    private void mSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSalirMouseClicked
       System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_mSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu mCiudades;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenu mDirectorio;
    private javax.swing.JMenu mSalir;
    private javax.swing.JMenuItem miAgregarCiudad;
    private javax.swing.JMenuItem miAgregarcliente;
    private javax.swing.JMenuItem miBuscarCliente;
    // End of variables declaration//GEN-END:variables
}
